/**
 * entitySlice — lecturers, rooms and faculties (master data).
 *
 * Uses createEntityAdapter so each collection has normalized state:
 * { ids: string[], entities: Record<string, T> }
 * This gives us fast O(1) lookups by ID, which the timetable grid needs.
 */
import {
	createEntityAdapter,
	createSlice,
	type PayloadAction,
} from '@reduxjs/toolkit'
import type {
	CreateFacultyInput,
	CreateLecturerInput,
	CreateRoomInput,
	Faculty,
	Lecturer,
	Room,
	UpdateFacultyInput,
	UpdateLecturerInput,
	UpdateRoomInput,
} from '@/types'
import type { RootState } from './index'

// ─── ID generator (same as before) ───────────────────────────────────────────

function generateId(): string {
	return `${Date.now()}-${Math.random().toString(36).slice(2)}`
}

// ─── Entity adapters ──────────────────────────────────────────────────────────

const lecturersAdapter = createEntityAdapter<Lecturer>()
const roomsAdapter     = createEntityAdapter<Room>()
const facultiesAdapter = createEntityAdapter<Faculty>()

// ─── Slice ────────────────────────────────────────────────────────────────────

const entitySlice = createSlice({
	name: 'entities',
	initialState: {
		lecturers: lecturersAdapter.getInitialState(),
		rooms:     roomsAdapter.getInitialState(),
		faculties: facultiesAdapter.getInitialState(),
	},
	reducers: {
		// ── Lecturers ──────────────────────────────────────────────────────────
		addLecturer(state, action: PayloadAction<CreateLecturerInput>) {
			const lecturer: Lecturer = {
				...action.payload,
				id: generateId(),
				createdAt: new Date(),
				updatedAt: new Date(),
			}
			lecturersAdapter.addOne(state.lecturers, lecturer)
		},
		updateLecturer(
			state,
			action: PayloadAction<{ id: string; updates: UpdateLecturerInput }>
		) {
			const { id, updates } = action.payload
			lecturersAdapter.updateOne(state.lecturers, {
				id,
				changes: { ...updates, updatedAt: new Date() },
			})
		},
		deleteLecturer(state, action: PayloadAction<string>) {
			lecturersAdapter.removeOne(state.lecturers, action.payload)
		},

		// ── Rooms ──────────────────────────────────────────────────────────────
		addRoom(state, action: PayloadAction<CreateRoomInput>) {
			const room: Room = {
				...action.payload,
				id: generateId(),
				createdAt: new Date(),
				updatedAt: new Date(),
			}
			roomsAdapter.addOne(state.rooms, room)
		},
		updateRoom(
			state,
			action: PayloadAction<{ id: string; updates: UpdateRoomInput }>
		) {
			const { id, updates } = action.payload
			roomsAdapter.updateOne(state.rooms, {
				id,
				changes: { ...updates, updatedAt: new Date() },
			})
		},
		deleteRoom(state, action: PayloadAction<string>) {
			roomsAdapter.removeOne(state.rooms, action.payload)
		},

		// ── Faculties ──────────────────────────────────────────────────────────
		addFaculty(state, action: PayloadAction<CreateFacultyInput>) {
			const faculty: Faculty = {
				...action.payload,
				id: generateId(),
				createdAt: new Date(),
				updatedAt: new Date(),
			}
			facultiesAdapter.addOne(state.faculties, faculty)
		},
		updateFaculty(
			state,
			action: PayloadAction<{ id: string; updates: UpdateFacultyInput }>
		) {
			const { id, updates } = action.payload
			facultiesAdapter.updateOne(state.faculties, {
				id,
				changes: { ...updates, updatedAt: new Date() },
			})
		},
		deleteFaculty(state, action: PayloadAction<string>) {
			facultiesAdapter.removeOne(state.faculties, action.payload)
		},
	},
})

export const {
	addLecturer, updateLecturer, deleteLecturer,
	addRoom,     updateRoom,     deleteRoom,
	addFaculty,  updateFaculty,  deleteFaculty,
} = entitySlice.actions

export default entitySlice.reducer

// ─── Selectors (generated by adapter) ────────────────────────────────────────

const lecturerSelectors = lecturersAdapter.getSelectors(
	(state: RootState) => state.entities.lecturers
)
const roomSelectors = roomsAdapter.getSelectors(
	(state: RootState) => state.entities.rooms
)
const facultySelectors = facultiesAdapter.getSelectors(
	(state: RootState) => state.entities.faculties
)

export const selectAllLecturers  = lecturerSelectors.selectAll
export const selectLecturerById  = lecturerSelectors.selectById
export const selectLecturerIds   = lecturerSelectors.selectIds

export const selectAllRooms      = roomSelectors.selectAll
export const selectRoomById      = roomSelectors.selectById

export const selectAllFaculties  = facultySelectors.selectAll
export const selectFacultyById   = facultySelectors.selectById
